changelog:
  categories:
    - title: "🚀 Features"
      labels: [feature]
    - title: "🐛 Bug Fixes"
      labels: [bug]
    - title: "🏗️ Infrastructure"
      labels: [infrastructure]
    - title: "📦 Packaging"
      labels: [packaging]
    - title: "📖 Documentation"
      labels: [documentation]
    - title: "Other Changes"
      labels: ["*"]
  exclude:
    labels: [skip-changelog]
