/**
 * AUTO-GENERATED -- DO NOT EDIT BY HAND.
 *
 * Written by `scripts/sync-pieces-catalog.ts`: for each verified piece, the
 * actions of the version the catalog installs, read from the published
 * package. `governed-pieces.test.ts` requires every action here to be mapped
 * by the piece's adapter in `src/workflows/runtime/piece-effects.ts`.
 *
 * To refresh without a full sync:  bun run scripts/sync-pieces-catalog.ts --manifests-only
 */

export interface VerifiedManifest {
  version: string;
  /** Upstream classification is READ | SEARCH | WRITE | DESTRUCTIVE, or null. */
  actions: Array<{ name: string; classification: string | null; props: string[] }>;
}

export const VERIFIED_MANIFESTS: Record<string, VerifiedManifest> = {
  "claude": {
    version: "0.7.0",
    actions: [
      {"name":"ask_claude","classification":"READ","props":["image","maxTokens","model","prompt","roles","systemPrompt","temperature","thinkingMode","thinkingModeParams"]},
      {"name":"cancel_message_batch","classification":"WRITE","props":["messageBatchId"]},
      {"name":"count_tokens","classification":"READ","props":["model","prompt","systemPrompt"]},
      {"name":"create_message_batch","classification":"WRITE","props":["requests"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_message_batch","classification":"DESTRUCTIVE","props":["messageBatchId"]},
      {"name":"extract-structured-data","classification":"READ","props":["image","maxTokens","mode","model","prompt","schema","text"]},
      {"name":"get_message_batch","classification":"READ","props":["messageBatchId"]},
      {"name":"get_message_batch_results","classification":"READ","props":["maxResults","messageBatchId"]},
      {"name":"get_model","classification":"READ","props":["modelId"]},
      {"name":"list_message_batches","classification":"SEARCH","props":["afterId","beforeId","limit"]},
      {"name":"list_models","classification":"SEARCH","props":[]},
    ],
  },
  "discord": {
    version: "0.7.0",
    actions: [
      {"name":"add_role_to_member","classification":"WRITE","props":["guild_id","role_id","user_id"]},
      {"name":"ban_guild_member","classification":"DESTRUCTIVE","props":["ban_reason","guild_id","user_id"]},
      {"name":"create_channel","classification":"WRITE","props":["guild_id","name","topic"]},
      {"name":"createGuildRole","classification":"WRITE","props":["creation_reason","display_separated","guild_id","role_color","role_mentionable","role_name"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_channel","classification":"DESTRUCTIVE","props":["channel_id"]},
      {"name":"deleteGuildRole","classification":"DESTRUCTIVE","props":["deletion_reason","guild_id","role_id"]},
      {"name":"discord_add_reaction","classification":"WRITE","props":["channel_id","emoji","message_id"]},
      {"name":"discord_add_role","classification":"WRITE","props":["guild_id","role_id","user_id"]},
      {"name":"discord_add_thread_member","classification":"WRITE","props":["channel_id","user_id"]},
      {"name":"discord_bulk_delete_messages","classification":"DESTRUCTIVE","props":["channel_id","message_ids"]},
      {"name":"discord_clear_reactions","classification":"DESTRUCTIVE","props":["channel_id","message_id"]},
      {"name":"discord_create_channel","classification":"WRITE","props":["guild_id","name","topic"]},
      {"name":"discord_create_dm","classification":"WRITE","props":["user_id"]},
      {"name":"discord_create_role","classification":"WRITE","props":["color","guild_id","hoist","mentionable","name","reason"]},
      {"name":"discord_create_scheduled_event","classification":"WRITE","props":["channel_id","description","entity_type","guild_id","location","name","scheduled_end_time","scheduled_start_time"]},
      {"name":"discord_create_thread","classification":"WRITE","props":["auto_archive_duration","channel_id","message","name","type"]},
      {"name":"discord_create_thread_from_message","classification":"WRITE","props":["auto_archive_duration","channel_id","message_id","name"]},
      {"name":"discord_delete_channel","classification":"DESTRUCTIVE","props":["channel_id"]},
      {"name":"discord_delete_message","classification":"DESTRUCTIVE","props":["channel_id","message_id","reason"]},
      {"name":"discord_delete_role","classification":"DESTRUCTIVE","props":["guild_id","reason","role_id"]},
      {"name":"discord_delete_scheduled_event","classification":"DESTRUCTIVE","props":["event_id","guild_id"]},
      {"name":"discord_edit_message","classification":"WRITE","props":["channel_id","content","message_id"]},
      {"name":"discord_find_channel","classification":"SEARCH","props":["guild_id","name"]},
      {"name":"discord_find_member","classification":"SEARCH","props":["guild_id","limit","query"]},
      {"name":"discord_get_channel","classification":"READ","props":["channel_id"]},
      {"name":"discord_get_guild","classification":"READ","props":["guild_id","with_counts"]},
      {"name":"discord_get_member","classification":"READ","props":["guild_id","user_id"]},
      {"name":"discord_get_user","classification":"READ","props":["user_id"]},
      {"name":"discord_join_thread","classification":"WRITE","props":["channel_id"]},
      {"name":"discord_leave_thread","classification":"WRITE","props":["channel_id"]},
      {"name":"discord_list_active_threads","classification":"SEARCH","props":["guild_id"]},
      {"name":"discord_list_archived_threads","classification":"SEARCH","props":["channel_id"]},
      {"name":"discord_list_bans","classification":"SEARCH","props":["after","before","guild_id","limit"]},
      {"name":"discord_list_channels","classification":"SEARCH","props":["guild_id"]},
      {"name":"discord_list_emojis","classification":"SEARCH","props":["guild_id"]},
      {"name":"discord_list_invites","classification":"SEARCH","props":["guild_id"]},
      {"name":"discord_list_messages","classification":"SEARCH","props":["after","around","before","channel_id","limit"]},
      {"name":"discord_list_pinned_messages","classification":"SEARCH","props":["channel_id"]},
      {"name":"discord_list_reactions","classification":"SEARCH","props":["after","channel_id","emoji","limit","message_id"]},
      {"name":"discord_list_roles","classification":"SEARCH","props":["guild_id"]},
      {"name":"discord_list_scheduled_events","classification":"SEARCH","props":["guild_id","with_user_count"]},
      {"name":"discord_pin_message","classification":"WRITE","props":["channel_id","message_id"]},
      {"name":"discord_remove_reaction","classification":"WRITE","props":["channel_id","emoji","message_id"]},
      {"name":"discord_remove_role","classification":"WRITE","props":["guild_id","role_id","user_id"]},
      {"name":"discord_remove_user_reaction","classification":"WRITE","props":["channel_id","emoji","message_id","user_id"]},
      {"name":"discord_rename_channel","classification":"WRITE","props":["channel_id","name"]},
      {"name":"discord_revoke_invite","classification":"DESTRUCTIVE","props":["invite_code"]},
      {"name":"discord_send_message","classification":"WRITE","props":["channel_id","content","files"]},
      {"name":"discord_unpin_message","classification":"WRITE","props":["channel_id","message_id"]},
      {"name":"discord_update_role","classification":"WRITE","props":["color","guild_id","hoist","mentionable","name","reason","role_id"]},
      {"name":"discord_update_scheduled_event","classification":"DESTRUCTIVE","props":["description","event_id","guild_id","name","scheduled_start_time","status"]},
      {"name":"find_channel","classification":"SEARCH","props":["guild_id","name"]},
      {"name":"list_guild_members","classification":"SEARCH","props":["guild_id","shortText"]},
      {"name":"remove_ban_from_user","classification":"WRITE","props":["guild_id","unban_reason","user_id"]},
      {"name":"remove_member_from_guild","classification":"DESTRUCTIVE","props":["guild_id","user_id"]},
      {"name":"remove_role_from_member","classification":"WRITE","props":["guild_id","role_id","user_id"]},
      {"name":"rename_channel","classification":"WRITE","props":["channel_id","name"]},
      {"name":"request_approval_message","classification":"WRITE","props":["channel","content"]},
      {"name":"send_message_webhook","classification":"WRITE","props":["avatar_url","content","embeds","tts","username","webhook_url"]},
      {"name":"sendMessageWithBot","classification":"WRITE","props":["channel_id","files","message"]},
    ],
  },
  "github": {
    version: "0.7.3",
    actions: [
      {"name":"add_labels_to_issue","classification":null,"props":["issue_number","labels","repository"]},
      {"name":"create_branch","classification":null,"props":["new_branch_name","repository","source_branch"]},
      {"name":"createCommentOnAIssue","classification":null,"props":["comment","issue_number","repository"]},
      {"name":"custom_api_call","classification":null,"props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_branch","classification":null,"props":["branch","repository"]},
      {"name":"find_branch","classification":null,"props":["branch","repository"]},
      {"name":"find_issue","classification":null,"props":["repository","state","title"]},
      {"name":"find_user","classification":null,"props":["username"]},
      {"name":"getIssueInformation","classification":null,"props":["issue_number","repository"]},
      {"name":"github_create_commit_comment","classification":null,"props":["body","path","position","repository","sha"]},
      {"name":"github_create_discussion_comment","classification":null,"props":["body","discussion_number","repository"]},
      {"name":"github_create_gist","classification":null,"props":["content","description","filename","public"]},
      {"name":"github_create_issue","classification":null,"props":["assignees","description","labels","repository","title"]},
      {"name":"github_create_pull_request_review_comment","classification":null,"props":["body","commit_id","path","position","pull_number","repository"]},
      {"name":"lockIssue","classification":null,"props":["issue_number","lock_reason","repository"]},
      {"name":"rawGraphqlQuery","classification":null,"props":["query","variables"]},
      {"name":"unlockIssue","classification":null,"props":["issue_number","repository"]},
      {"name":"update_issue","classification":null,"props":["assignees","body","issue_number","labels","milestone","repository","state","state_reason","title"]},
    ],
  },
  "gmail": {
    version: "0.17.0",
    actions: [
      {"name":"create_draft_reply","classification":"WRITE","props":["attachment","attachment_name","body","body_type","include_original_message","message_id","reply_type","sender_name"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"gmail_add_label_to_email","classification":"WRITE","props":["label","message_id"]},
      {"name":"gmail_archive_email","classification":"WRITE","props":["message_id"]},
      {"name":"gmail_archive_message","classification":"WRITE","props":["message_id"]},
      {"name":"gmail_create_draft","classification":"WRITE","props":["attachments","bcc","body","body_type","cc","from","receiver","sender_name","subject","thread_id"]},
      {"name":"gmail_create_label","classification":"WRITE","props":["name"]},
      {"name":"gmail_delete_draft","classification":"DESTRUCTIVE","props":["draft_id"]},
      {"name":"gmail_forward_message","classification":"WRITE","props":["bcc","cc","message_id","note","receiver","sender_name"]},
      {"name":"gmail_get_attachment","classification":"READ","props":["attachment_id","file_name","message_id"]},
      {"name":"gmail_get_draft","classification":"READ","props":["draft_id"]},
      {"name":"gmail_get_label","classification":"READ","props":["label_id"]},
      {"name":"gmail_get_mail","classification":"READ","props":["message_id"]},
      {"name":"gmail_get_message","classification":"READ","props":["message_id"]},
      {"name":"gmail_get_or_create_label","classification":"WRITE","props":["name"]},
      {"name":"gmail_get_profile","classification":"READ","props":[]},
      {"name":"gmail_get_thread","classification":"READ","props":["format","thread_id"]},
      {"name":"gmail_list_drafts","classification":"SEARCH","props":["max_results","query"]},
      {"name":"gmail_list_history","classification":"SEARCH","props":["history_types","max_results","start_history_id"]},
      {"name":"gmail_list_labels","classification":"SEARCH","props":[]},
      {"name":"gmail_list_threads","classification":"SEARCH","props":["include_spam_trash","label_ids","max_results","query"]},
      {"name":"gmail_modify_labels","classification":"WRITE","props":["add_label_ids","message_ids","remove_label_ids"]},
      {"name":"gmail_modify_thread_labels","classification":"WRITE","props":["add_label_ids","remove_label_ids","thread_id"]},
      {"name":"gmail_remove_label_from_email","classification":"WRITE","props":["label","message_id"]},
      {"name":"gmail_reply_to_thread","classification":"WRITE","props":["attachment","attachment_name","body","body_type","message_id","reply_type","sender_name"]},
      {"name":"gmail_search_email","classification":"SEARCH","props":["after_date","attachment_name","before_date","category","content","from","has_attachment","include_spam_trash","label","max_results","subject","to"]},
      {"name":"gmail_search_mail","classification":"SEARCH","props":["after_date","attachment_name","before_date","category","content","from","has_attachment","include_spam_trash","label","max_results","subject","to"]},
      {"name":"gmail_send_draft","classification":"WRITE","props":["draft_id"]},
      {"name":"gmail_send_email","classification":"WRITE","props":["attachments","bcc","body","body_type","cc","draft","from","in_reply_to","receiver","reply_to","sender_name","subject"]},
      {"name":"gmail_stop_watch","classification":"DESTRUCTIVE","props":[]},
      {"name":"gmail_trash_message","classification":"WRITE","props":["message_id"]},
      {"name":"gmail_untrash_message","classification":"WRITE","props":["message_id"]},
      {"name":"gmail_update_draft","classification":"WRITE","props":["attachments","bcc","body","body_type","cc","draft_id","from","receiver","sender_name","subject","thread_id"]},
      {"name":"gmail_update_label","classification":"WRITE","props":["background_color","label_id","label_list_visibility","message_list_visibility","name","text_color"]},
      {"name":"reply_to_email","classification":"WRITE","props":["attachment","attachment_name","body","body_type","message_id","reply_type","sender_name"]},
      {"name":"request_approval_in_mail","classification":"WRITE","props":["attachments","bcc","body","body_type","cc","from","in_reply_to","receiver","reply_to","sender_name","subject"]},
      {"name":"send_email","classification":"WRITE","props":["attachments","bcc","body","body_type","cc","draft","from","in_reply_to","receiver","reply_to","sender_name","subject"]},
    ],
  },
  "google-calendar": {
    version: "0.12.0",
    actions: [
      {"name":"create_google_calendar_event","classification":"WRITE","props":["attendees","calendar_id","colorId","create_meet_link","description","end_date_time","guests_can_invite_others","guests_can_modify","guests_can_see_other_guests","location","send_notifications","start_date_time","title"]},
      {"name":"create_quick_event","classification":"WRITE","props":["calendar_id","send_updates","text"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_event","classification":"DESTRUCTIVE","props":["calendar_id","eventId"]},
      {"name":"google_calendar_create_event","classification":"WRITE","props":["attendees","calendar_id","colorId","create_meet_link","description","end_date_time","guests_can_invite_others","guests_can_modify","guests_can_see_other_guests","location","send_notifications","start_date_time","title"]},
      {"name":"google_calendar_delete_event","classification":"DESTRUCTIVE","props":["calendar_id","event_id"]},
      {"name":"google_calendar_find_busy_free_periods","classification":"SEARCH","props":["calendar_ids","end_date","start_date"]},
      {"name":"google_calendar_find_busy_periods","classification":"SEARCH","props":["calendar_ids","end_date","start_date"]},
      {"name":"google_calendar_find_free_slots","classification":"SEARCH","props":["calendar_ids","end_date","min_duration_minutes","start_date","working_hours_end","working_hours_start"]},
      {"name":"google_calendar_get_calendar","classification":"READ","props":["calendar_id"]},
      {"name":"google_calendar_get_colors","classification":"READ","props":[]},
      {"name":"google_calendar_get_event","classification":"READ","props":["calendar_id","event_id","max_attendees","time_zone"]},
      {"name":"google_calendar_get_event_by_id","classification":"READ","props":["calendar_id","event_id","max_attendees","time_zone"]},
      {"name":"google_calendar_get_events","classification":"SEARCH","props":["calendar_id","end_date","event_types","search","singleEvents","start_date"]},
      {"name":"google_calendar_import_event","classification":"WRITE","props":["calendar_id","description","end_date_time","ical_uid","location","start_date_time","summary"]},
      {"name":"google_calendar_list_calendars","classification":"SEARCH","props":[]},
      {"name":"google_calendar_list_events","classification":"SEARCH","props":["calendar_id","end_date","event_types","search","singleEvents","start_date"]},
      {"name":"google_calendar_list_recurring_event_instances","classification":"SEARCH","props":["calendar_id","event_id","max_results","show_deleted","time_max","time_min"]},
      {"name":"google_calendar_list_settings","classification":"SEARCH","props":[]},
      {"name":"google_calendar_move_event","classification":"WRITE","props":["calendar_id","destination_calendar_id","event_id","send_updates"]},
      {"name":"google_calendar_remove_attendee","classification":"WRITE","props":["attendee_email","calendar_id","event_id","send_updates"]},
      {"name":"google_calendar_search_events_all_calendars","classification":"SEARCH","props":["end_date","query","single_events","start_date"]},
      {"name":"google_calendar_update_event","classification":"WRITE","props":["attendees","calendar_id","colorId","description","end_date_time","event_id","guests_can_invite_others","guests_can_modify","guests_can_see_other_guests","location","start_date_time","title"]},
      {"name":"google-calendar-add-attendees","classification":"WRITE","props":["attendees","calendar_id","eventId"]},
      {"name":"update_event","classification":"WRITE","props":["attendees","calendar_id","colorId","description","end_date_time","eventId","guests_can_invite_others","guests_can_modify","guests_can_see_other_guests","hint","location","start_date_time","title"]},
    ],
  },
  "google-drive": {
    version: "0.11.0",
    actions: [
      {"name":"create_new_gdrive_file","classification":"WRITE","props":["fileName","fileType","include_team_drives","parentFolder","text"]},
      {"name":"create_new_gdrive_folder","classification":"WRITE","props":["folderName","include_team_drives","parentFolder"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_gdrive_file","classification":"DESTRUCTIVE","props":["fileId","include_team_drives"]},
      {"name":"delete_permissions","classification":"DESTRUCTIVE","props":["fileId","permission_name","user_email"]},
      {"name":"drive_copy_file","classification":"WRITE","props":["convert_to","file_id","folder_id","name"]},
      {"name":"drive_create_comment","classification":"WRITE","props":["content","file_id"]},
      {"name":"drive_create_file_from_text","classification":"WRITE","props":["content_type","file_name","parent_folder_id","text"]},
      {"name":"drive_create_folder","classification":"WRITE","props":["folder_name","parent_folder_id"]},
      {"name":"drive_create_reply","classification":"WRITE","props":["action","comment_id","content","file_id"]},
      {"name":"drive_create_shared_drive","classification":"WRITE","props":["name"]},
      {"name":"drive_delete_file","classification":"DESTRUCTIVE","props":["file_id"]},
      {"name":"drive_delete_reply","classification":"DESTRUCTIVE","props":["comment_id","file_id","reply_id"]},
      {"name":"drive_delete_shared_drive","classification":"DESTRUCTIVE","props":["drive_id"]},
      {"name":"drive_download_file","classification":"READ","props":["destination_file_name","file_id"]},
      {"name":"drive_empty_trash","classification":"DESTRUCTIVE","props":["drive_id"]},
      {"name":"drive_export_folder_as_zip","classification":"READ","props":["duplicatePathWarning","folderId","googleDocsFormat","googleSheetsFormat","googleSlidesFormat","includeTeamDrives","outputFileName","passwordOptions","usePassword"]},
      {"name":"drive_export_workspace_file","classification":"READ","props":["file_id","mime_type"]},
      {"name":"drive_get_about","classification":"READ","props":[]},
      {"name":"drive_get_file","classification":"READ","props":["file_id"]},
      {"name":"drive_get_reply","classification":"READ","props":["comment_id","file_id","reply_id"]},
      {"name":"drive_get_shared_drive","classification":"READ","props":["drive_id"]},
      {"name":"drive_list_comments","classification":"SEARCH","props":["file_id"]},
      {"name":"drive_list_files","classification":"SEARCH","props":["depth_level","download_files","folder_id","include_team_drives","include_trashed"]},
      {"name":"drive_list_permissions","classification":"SEARCH","props":["file_id"]},
      {"name":"drive_list_replies","classification":"SEARCH","props":["comment_id","file_id"]},
      {"name":"drive_list_shared_drives","classification":"SEARCH","props":["page_size","query"]},
      {"name":"drive_move_file","classification":"WRITE","props":["file_id","folder_id"]},
      {"name":"drive_remove_permission","classification":"DESTRUCTIVE","props":["file_id","role","user_email"]},
      {"name":"drive_replace_file_content","classification":"WRITE","props":["file","file_id","mime_type"]},
      {"name":"drive_save_file_as_pdf","classification":"WRITE","props":["document_id","folder_id","name"]},
      {"name":"drive_search_files","classification":"SEARCH","props":["include_team_drives","operator","parent_folder_id","query_term","type","value"]},
      {"name":"drive_set_public_access","classification":"WRITE","props":["file_id","role"]},
      {"name":"drive_share_file","classification":"WRITE","props":["file_id","role","send_invitation_email","user_email"]},
      {"name":"drive_trash_file","classification":"DESTRUCTIVE","props":["file_id"]},
      {"name":"drive_untrash_file","classification":"WRITE","props":["file_id"]},
      {"name":"drive_update_file_metadata","classification":"WRITE","props":["description","file_id","name","starred"]},
      {"name":"drive_update_permission","classification":"WRITE","props":["file_id","new_role","user_email"]},
      {"name":"drive_update_reply","classification":"WRITE","props":["comment_id","content","file_id","reply_id"]},
      {"name":"drive_update_shared_drive","classification":"WRITE","props":["drive_id","name"]},
      {"name":"drive_upload_file","classification":"WRITE","props":["file","file_name","parent_folder_id"]},
      {"name":"drive_upload_from_url","classification":"WRITE","props":["file_name","mime_type","parent_folder_id","source_url"]},
      {"name":"duplicate_file","classification":"WRITE","props":["fileId","folderId","include_team_drives","mimeType","name"]},
      {"name":"get-file-or-folder-by-id","classification":"READ","props":["id","include_team_drives"]},
      {"name":"google-drive-move-file","classification":"WRITE","props":["fileId","folderId","include_team_drives"]},
      {"name":"list-files","classification":"SEARCH","props":["depthLevel","downloadFiles","folderId","includeTrashed","include_team_drives"]},
      {"name":"read-file","classification":"READ","props":["fileId","fileName"]},
      {"name":"save_file_as_pdf","classification":"WRITE","props":["documentId","folderId","include_team_drives","name"]},
      {"name":"search-folder","classification":"SEARCH","props":["include_team_drives","operator","parentFolder","query","queryTerm","type"]},
      {"name":"set_public_access","classification":"WRITE","props":["fileId","role"]},
      {"name":"trash_gdrive_file","classification":"DESTRUCTIVE","props":["fileId","include_team_drives"]},
      {"name":"update_permissions","classification":"WRITE","props":["fileId","include_team_drives","permission_name","send_invitation_email","user_email"]},
      {"name":"upload_gdrive_file","classification":"WRITE","props":["file","fileName","include_team_drives","parentFolder"]},
    ],
  },
  "notion": {
    version: "0.7.3",
    actions: [
      {"name":"add_comment","classification":"WRITE","props":["comment_text","page_id"]},
      {"name":"append_to_page","classification":"WRITE","props":["content","pageId"]},
      {"name":"archive_database_item","classification":"DESTRUCTIVE","props":["database_id","database_item_id"]},
      {"name":"create_database_item","classification":"WRITE","props":["content","databaseFields","database_id"]},
      {"name":"createPage","classification":"WRITE","props":["content","pageId","title"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"find_page","classification":"SEARCH","props":["exact_match","limit","title"]},
      {"name":"get_page_comments","classification":"READ","props":["page_id"]},
      {"name":"getPageOrBlockChildren","classification":"READ","props":["dynamic","markdown","parentId"]},
      {"name":"list_database_pages","classification":"SEARCH","props":["cursor","database_id","filterDatabaseFields","filter_hint","limit"]},
      {"name":"list_databases","classification":"SEARCH","props":["cursor","limit"]},
      {"name":"notion_add_comment","classification":"WRITE","props":["comment_text","page_id"]},
      {"name":"notion_append_to_page","classification":"WRITE","props":["block_id","content"]},
      {"name":"notion_archive_database_item","classification":"DESTRUCTIVE","props":["item_id"]},
      {"name":"notion_archive_page","classification":"DESTRUCTIVE","props":["archived","page_id"]},
      {"name":"notion_create_database","classification":"WRITE","props":["parent_page_id","properties","title"]},
      {"name":"notion_create_database_item","classification":"WRITE","props":["content","database_id","properties"]},
      {"name":"notion_create_page","classification":"WRITE","props":["content","parent_page_id","title"]},
      {"name":"notion_delete_block","classification":"DESTRUCTIVE","props":["block_id"]},
      {"name":"notion_find_database_item","classification":"SEARCH","props":["database_id","filter","page_size"]},
      {"name":"notion_get_block_children","classification":"READ","props":["block_id","depth","markdown"]},
      {"name":"notion_get_database","classification":"READ","props":["database_id"]},
      {"name":"notion_get_page","classification":"READ","props":["page_id"]},
      {"name":"notion_get_page_comments","classification":"READ","props":["page_id"]},
      {"name":"notion_get_user","classification":"READ","props":["user_id"]},
      {"name":"notion_list_users","classification":"SEARCH","props":["page_size","start_cursor"]},
      {"name":"notion_move_page","classification":"WRITE","props":["new_parent_database_id","new_parent_page_id","page_id"]},
      {"name":"notion_query_database","classification":"SEARCH","props":["database_id","filter","page_size","sorts","start_cursor"]},
      {"name":"notion_restore_database_item","classification":"WRITE","props":["item_id"]},
      {"name":"notion_search","classification":"SEARCH","props":["exact_match","filter_type","limit","query"]},
      {"name":"notion_update_block","classification":"WRITE","props":["block_id","block_type","checked","content","language"]},
      {"name":"notion_update_database_item","classification":"WRITE","props":["item_id","properties"]},
      {"name":"notion_update_database_schema","classification":"DESTRUCTIVE","props":["database_id","properties","title"]},
      {"name":"notion-find-database-item","classification":"SEARCH","props":["database_id","filterDatabaseFields","filter_hint"]},
      {"name":"restore_database_item","classification":"WRITE","props":["archived_item_id","database_id"]},
      {"name":"retrieve_database","classification":"READ","props":["database_id"]},
      {"name":"update_database_item","classification":"WRITE","props":["databaseFields","database_id","database_item_id"]},
    ],
  },
  "openai": {
    version: "0.12.0",
    actions: [
      {"name":"analyze_sentiment","classification":"READ","props":["model","text"]},
      {"name":"ask_assistant","classification":"WRITE","props":["assistant","memoryKey","prompt"]},
      {"name":"ask_chatgpt","classification":"READ","props":["frequencyPenalty","maxTokens","memoryKey","model","presencePenalty","prompt","roles","temperature","topP"]},
      {"name":"classify_text","classification":"READ","props":["input","model"]},
      {"name":"create_embedding","classification":"READ","props":["dimensions","input","model","user"]},
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"delete_file","classification":"DESTRUCTIVE","props":["fileId"]},
      {"name":"edit_image","classification":"READ","props":["image","mask","prompt","quality","size"]},
      {"name":"extract-structured-data","classification":"READ","props":["model","params","text"]},
      {"name":"find_file","classification":"SEARCH","props":["fileName","purpose"]},
      {"name":"generate_image","classification":"READ","props":["model","prompt","quality","resolution"]},
      {"name":"list_files","classification":"SEARCH","props":["limit","purpose"]},
      {"name":"list_models","classification":"SEARCH","props":["contains"]},
      {"name":"search_embeddings","classification":"READ","props":["documents","model","query","topK"]},
      {"name":"text_to_speech","classification":"READ","props":["fileName","format","model","speed","text","voice"]},
      {"name":"transcribe","classification":"READ","props":["audio","language"]},
      {"name":"translate","classification":"READ","props":["audio"]},
      {"name":"upload_file","classification":"WRITE","props":["file","fileName","purpose"]},
      {"name":"vision_prompt","classification":"READ","props":["detail","frequencyPenalty","image","maxTokens","presencePenalty","prompt","roles","temperature","topP"]},
    ],
  },
  "slack": {
    version: "0.21.0",
    actions: [
      {"name":"custom_api_call","classification":"WRITE","props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url","useUserToken"]},
      {"name":"delete-message","classification":"DESTRUCTIVE","props":["channel","info","onlyBotChannels","ts"]},
      {"name":"find_user_by_email","classification":"READ","props":["email"]},
      {"name":"find_user_by_handle","classification":"SEARCH","props":["handle"]},
      {"name":"find-user-by-id","classification":"READ","props":["id"]},
      {"name":"get_group_by_handle","classification":"READ","props":["handle"]},
      {"name":"get_user","classification":"READ","props":["id"]},
      {"name":"get-file","classification":"READ","props":["fileId"]},
      {"name":"get-message","classification":"READ","props":["channel","info","onlyBotChannels","ts"]},
      {"name":"getChannelHistory","classification":"SEARCH","props":["channel","includeAllMetadata","inclusive","info","latest","oldest","onlyBotChannels"]},
      {"name":"invite-user-to-channel","classification":"WRITE","props":["channel","info","onlyBotChannels","userId"]},
      {"name":"list_user_groups","classification":"SEARCH","props":["includeDisabled","includeUsers"]},
      {"name":"list_users","classification":"SEARCH","props":["includeBots","includeDisabled"]},
      {"name":"listUsers","classification":"SEARCH","props":["includeBots","includeDisabled"]},
      {"name":"markdownToSlackFormat","classification":"READ","props":["markdown"]},
      {"name":"request_action_direct_message","classification":"WRITE","props":["actions","mentionOriginFlow","profilePicture","text","userId","username"]},
      {"name":"request_action_message","classification":"WRITE","props":["actions","channel","info","mentionOriginFlow","onlyBotChannels","profilePicture","replyBroadcast","text","threadTs","username"]},
      {"name":"request_approval_direct_message","classification":"WRITE","props":["mentionOriginFlow","profilePicture","text","userId","username"]},
      {"name":"request_approval_message","classification":"WRITE","props":["channel","info","mentionOriginFlow","onlyBotChannels","profilePicture","text","username"]},
      {"name":"retrieveThreadMessages","classification":"READ","props":["channel","cursor","info","onlyBotChannels","threadTs"]},
      {"name":"searchMessages","classification":"SEARCH","props":["query"]},
      {"name":"send_channel_message","classification":"WRITE","props":["blocks","channel","file","iconEmoji","info","mentionOriginFlow","onlyBotChannels","profilePicture","replyBroadcast","sendAsBot","text","threadTs","unfurlLinks","username"]},
      {"name":"send_direct_message","classification":"WRITE","props":["blocks","iconEmoji","mentionOriginFlow","profilePicture","text","unfurlLinks","userId","username"]},
      {"name":"send_message_to_multiple_users","classification":"WRITE","props":["blocks","concurrency","iconEmoji","mentionOriginFlow","mode","profilePicture","recipients","unfurlLinks","username"]},
      {"name":"set_user_status","classification":"WRITE","props":["emoji","expiration","text"]},
      {"name":"set-channel-topic","classification":"WRITE","props":["channel","info","onlyBotChannels","topic"]},
      {"name":"slack_add_reaction","classification":"WRITE","props":["channel","info","onlyBotChannels","reactAsUser","reaction","ts"]},
      {"name":"slack_archive_channel","classification":"DESTRUCTIVE","props":["channel"]},
      {"name":"slack_close_dm","classification":"WRITE","props":["channel"]},
      {"name":"slack_create_channel","classification":"WRITE","props":["channelName","isPrivate"]},
      {"name":"slack_delete_message","classification":"DESTRUCTIVE","props":["channel","ts"]},
      {"name":"slack_delete_scheduled_message","classification":"DESTRUCTIVE","props":["channel","scheduledMessageId"]},
      {"name":"slack_find_channel","classification":"SEARCH","props":["excludeArchived","name"]},
      {"name":"slack_get_channel_history","classification":"SEARCH","props":["channel","inclusive","latest","oldest"]},
      {"name":"slack_get_channel_info","classification":"READ","props":["channel","includeNumMembers"]},
      {"name":"slack_get_file","classification":"READ","props":["fileId"]},
      {"name":"slack_get_message_permalink","classification":"READ","props":["channel","messageTs"]},
      {"name":"slack_get_reactions","classification":"READ","props":["channel","file","full","ts"]},
      {"name":"slack_get_thread_replies","classification":"SEARCH","props":["channel","cursor","threadTs"]},
      {"name":"slack_invite_users_to_channel","classification":"WRITE","props":["channel","userIds"]},
      {"name":"slack_join_channel","classification":"WRITE","props":["channel"]},
      {"name":"slack_leave_channel","classification":"WRITE","props":["channel"]},
      {"name":"slack_list_channel_members","classification":"SEARCH","props":["channel"]},
      {"name":"slack_list_channels","classification":"SEARCH","props":["excludeArchived","types"]},
      {"name":"slack_list_custom_emoji","classification":"SEARCH","props":[]},
      {"name":"slack_list_files","classification":"SEARCH","props":["channel","limit","ts_from","ts_to","types","user"]},
      {"name":"slack_list_scheduled_messages","classification":"SEARCH","props":["channel","latest","oldest"]},
      {"name":"slack_list_user_conversations","classification":"SEARCH","props":["excludeArchived","types","user"]},
      {"name":"slack_list_user_reactions","classification":"SEARCH","props":["limit","user"]},
      {"name":"slack_mark_conversation_read","classification":"WRITE","props":["channel","ts"]},
      {"name":"slack_post_message","classification":"WRITE","props":["blocks","channel","replyBroadcast","sendAsUser","text","threadTs","unfurlLinks"]},
      {"name":"slack_remove_reaction","classification":"WRITE","props":["channel","file","reactAsUser","reaction","ts"]},
      {"name":"slack_remove_user_from_channel","classification":"WRITE","props":["channel","user"]},
      {"name":"slack_rename_channel","classification":"WRITE","props":["channel","name"]},
      {"name":"slack_schedule_message","classification":"WRITE","props":["blocks","channel","postAt","text","threadTs"]},
      {"name":"slack_search_all","classification":"SEARCH","props":["query"]},
      {"name":"slack_search_messages","classification":"SEARCH","props":["query"]},
      {"name":"slack_send_direct_message","classification":"WRITE","props":["blocks","text","unfurlLinks","userId"]},
      {"name":"slack_send_ephemeral_message","classification":"WRITE","props":["blocks","channel","text","user"]},
      {"name":"slack_set_channel_purpose","classification":"WRITE","props":["channel","purpose"]},
      {"name":"slack_set_channel_topic","classification":"WRITE","props":["channel","topic"]},
      {"name":"slack_unarchive_channel","classification":"WRITE","props":["channel"]},
      {"name":"slack_update_message","classification":"WRITE","props":["blocks","channel","text","ts"]},
      {"name":"slack-add-reaction-to-message","classification":"WRITE","props":["channel","info","onlyBotChannels","reactAsUser","reaction","ts"]},
      {"name":"slack-create-channel","classification":"WRITE","props":["channelName","isPrivate"]},
      {"name":"slack-find-user-by-email","classification":"READ","props":["email"]},
      {"name":"slack-find-user-by-handle","classification":"SEARCH","props":["handle"]},
      {"name":"slack-set-user-status","classification":"WRITE","props":["emoji","expiration","text"]},
      {"name":"slack-update-profile","classification":"WRITE","props":["email","firstName","lastName","userId"]},
      {"name":"update_group_users","classification":"WRITE","props":["appendUsers","handle","userIds"]},
      {"name":"update_profile","classification":"WRITE","props":["email","firstName","lastName","userId"]},
      {"name":"updateMessage","classification":"WRITE","props":["blocks","channel","info","mentionOriginFlow","onlyBotChannels","text","ts"]},
      {"name":"uploadFile","classification":"WRITE","props":["channel","file","filename","onlyBotChannels","title"]},
    ],
  },
  "telegram-bot": {
    version: "0.5.7",
    actions: [
      {"name":"create_invite_link","classification":null,"props":["chat_id","expire_date","instructions","member_limit","name"]},
      {"name":"custom_api_call","classification":null,"props":["body","body_type","failsafe","followRedirects","headers","method","queryParams","response_is_binary","timeout","url"]},
      {"name":"get_chat_member","classification":null,"props":["chat_id","instructions","user_id"]},
      {"name":"get_file","classification":null,"props":["download","file_id"]},
      {"name":"request_approval_message","classification":null,"props":["approve_button_text","chat_id","disapprove_button_text","instructions","message","parse_mode"]},
      {"name":"send_media","classification":null,"props":["chat_id","format","instructions","instructions_format","media","media_type","message","message_thread_id","reply_markup"]},
      {"name":"send_text_message","classification":null,"props":["chat_id","format","instructions","instructions_format","message","message_thread_id","reply_markup","web_page_preview"]},
    ],
  },
};
