/**
 * Tool authority classification for relevance filtering.
 *
 * See docs/tool-relevance-filtering.md. This module owns the two axes the
 * filter reasons about and NOTHING else: no selection, no policy, no call
 * sites. Keeping it separate is what lets the invariant tests in
 * `invariant.test.ts` walk BUILTIN_TOOLS and assert properties of the
 * classification itself, independent of any heuristic.
 *
 * The filter exists to cut tool-schema tokens for small models. It is an
 * optimisation, never a control: the authority engine (src/authority) still
 * gates every call, and the ceiling of what the filter can offer is the full
 * registered set. What the filter CAN do wrong is steer the model away from
 * a framed tool and toward an unframed one, which is why this file exists.
 */

import type { ToolDefinition } from '../registry.ts';
import { TOOL_ACTION_MAP, getActionForTool, severityRank } from '../../../authority/tool-action-map.ts';
import { isUntrustedSourceTool } from '../../../roles/untrusted.ts';

/**
 * How a tool's result enters the context, and whether the model can aim the
 * tool at something outside the conversation.
 *
 *   framed  Result is delimiter-wrapped, defanged and (mostly) taint-marking
 *           -- `isUntrustedSourceTool` is true. Fully DERIVED, never declared,
 *           so it cannot drift from the real framing set.
 *   fetch   The model can direct it at content outside the conversation and
 *           the result is NOT framed. This is the laundering class: retaining
 *           one of these forces the framed readers to stay.
 *   replay  Returns stored text of mixed provenance, but the model cannot aim
 *           it outside -- it only reads back records this system already
 *           holds. See the long note below; this is a load-bearing judgement.
 *   inert   The model cannot aim it outside AND its result is generated by us
 *           or by a machine the owner paired.
 *
 * Note the definition of `inert`. An earlier version said "cannot carry
 * outside-authored text at all", which is FALSE in this codebase for most of
 * the set: `write_file`, `set_clipboard` and `get_system_info` all begin with
 * `const target = params.target ?? autoTargetForCapability(...)` and, on any
 * install with a matching sidecar, return the remote's reply verbatim with no
 * model input at all. What actually separates `inert` from `fetch` is
 * AIMABILITY -- whether the model can point the tool at content of its own
 * choosing -- and that is the property the invariant depends on.
 *
 * `reach` is the WORST reach across all of a tool's actions. Most of these
 * tools are action multiplexers (`manage_goals` has 17), so a new action can
 * change the classification of the whole tool. Adding one means re-deciding.
 */
export type OutsideReach = 'framed' | 'fetch' | 'replay' | 'inert';

/**
 * Why `replay` is on the safe side of the framing invariant.
 *
 * The hazard this filter must not create is SUBSTITUTION: the model wants to
 * read something from outside, the framed route has been filtered away, so it
 * takes an unframed route instead and the content arrives unwrapped. That is
 * what #475 did by dropping every browser tool while keeping `run_command`.
 *
 * The test is therefore NOT "can this tool's output contain outside-authored
 * bytes" -- almost everything can, once a web page has been summarised into a
 * note. The test is "can the model aim this tool at content of its own
 * choosing from outside the conversation". No model asked to summarise a URL
 * calls `commitments` instead; it cannot point `commitments` at a URL.
 *
 * Two consequences, both enforced below:
 *   1. replay tools are never floor-eligible. An earlier draft of this design
 *      put them in the always-set, which is strictly worse than the status
 *      quo: it pins a tool that echoes stored outside text into every turn.
 *   2. replay tools do not trigger the framing union, so a "remind me" turn
 *      does not have to carry 9.7 kB of browser schema it cannot use.
 */
const REPLAY_TOOLS: ReadonlySet<string> = new Set([
  // `list` and `delete` only. Parameter names in the listing come from
  // accessible names on recorded surfaces, so the text is of outside origin
  // -- but `manage_skills` cannot record or run anything (that is
  // record_skill / run_skill, both framed), so it cannot be aimed.
  'manage_skills',
  // Vault documents: create/get/list/update/append/delete. No URL, no path,
  // no source, no import; `list.search` searches the local vault only.
  'create_document',
  // Pipeline items. `get` returns `item.body`, which may hold research
  // output, but none of the ten actions takes a URL or a path, and nothing
  // watches stage transitions -- reaching the `published` stage only moves a
  // string column. A future `publish` action that actually published would
  // make this `fetch`; see the worst-action rule above.
  'content_pipeline',
  // create/decompose/replan/estimate/morning_plan/evening_review and friends
  // all operate on local goal rows through an internal LLM call. No HTTP, no
  // path, no enqueue. Goals CAN mint commitments, but only through
  // goals/work-items.ts, which registers them in `commitment_work`, and the
  // executor's getDueCommitments({excludeWorkItems:true}) skips those -- so
  // the hazard that puts `commitments` in `fetch` does not reach here.
  'manage_goals',
  // Remote-authored, but not aimable: hostname, os, capabilities and each
  // unavailable capability's `reason` come straight off the sidecar's own
  // register / capabilities_update frame with no validation. The model
  // chooses nothing, so it is not a substitution route -- but it is emphatically
  // not `inert`, and it must not sit in a floor that no input can remove.
  'list_sidecars',
]);

/**
 * Tools the agent loops append that are not in any registry.
 *
 * `discover_tools` lists tool names; `ask_for_clarification` asks the person
 * a question. Neither can be aimed at anything and neither carries authority
 * of its own, so both are `inert` and rank 100 by fiat (see `authorityRank`).
 * They remain floor-ineligible because `isFloorEligible` demands an explicit
 * TOOL_ACTION_MAP entry, which by definition they do not have.
 */
export const SYNTHETIC_TOOLS: ReadonlySet<string> = new Set([
  'discover_tools',
  'ask_for_clarification',
]);

/**
 * Two tools that LOOK like `replay` and are deliberately NOT.
 *
 * They fall through to the `fetch` default; this set exists only so the
 * reasoning is recorded where someone would otherwise "tidy" them into
 * REPLAY_TOOLS alongside their obvious siblings.
 *
 *   commitments
 *     `create(what, when_due)` schedules an unattended agent turn whose
 *     ENTIRE TEXT the model writes. A commitment made by this tool has no
 *     `commitment_work` row, so the executor's
 *     getDueCommitments({excludeWorkItems:true}) picks it up and
 *     executeCommitment dispatches `handleMessage(prompt, 'system')` with
 *     "[COMMITMENT EXECUTION - MANDATORY] ... Execute it NOW using your
 *     tools ... browser, terminal, file operations". The default cancel
 *     window is 5 seconds (heartbeat aggressiveness defaults to
 *     'aggressive'). The output comes back through `commitments get` as
 *     `Result: ...`, unframed.
 *
 *     So it is aimable in the strongest sense available in this product:
 *     not a choice among stored workflows the way `manage_workflow` is, but
 *     free text executed with no human turn in between. That is a wider
 *     version of what `discover_tools({names})` is hardened for, and it must
 *     not be the one tool left standing on a "remind me" turn.
 *
 *   research_queue
 *     `add(topic, ...)` enqueues work and `list` replays a stored `result`.
 *     It is inert TODAY only because its consumer is dead code:
 *     ResearchQueue.getNext/startResearch/complete have no callers since the
 *     heartbeat was removed, so `result` is never populated. The class, the
 *     tool and the daemon wiring all still exist for someone to re-land. A
 *     URL is a legal `topic`. Classifying it on the current absence of a
 *     worker would make the safety of this filter depend on a deletion
 *     nothing enforces, so it is `fetch` and costs 859 bytes.
 */
const NOT_REPLAY_DESPITE_APPEARANCES: ReadonlySet<string> = new Set([
  'commitments',
  'research_queue',
]);

/**
 * Tools the model cannot aim outside, whose result we or a paired machine
 * generate.
 *
 * Only these are floor-eligible, and only if they also clear the rank and
 * explicit-mapping tests in `isFloorEligible`. Getting an entry wrong here is
 * the worst error possible in this design, because no input can remove a
 * floor tool -- so each entry names what it actually returns.
 */
const INERT_TOOLS: ReadonlySet<string> = new Set([
  // Not floor-eligible (rank 302), but correctly inert: the model picks the
  // path and the content, yet cannot point either at anything outside. On an
  // install with a filesystem sidecar these return the remote's reply rather
  // than a local status, which is why `inert` is defined by aimability.
  'write_file',
  'set_clipboard',
  // Hostname/platform/arch/cpu/version. Routed to a sidecar when one is
  // paired, so "generated locally" is not always true -- but the model
  // chooses nothing about it.
  'get_system_info',
  // The intent-gate tool. Echoes the model's own `intent` and one of
  // [APPROVED]/[DENIED]/[EXPIRED]/[PENDING]; no user-supplied note reaches
  // the returned string.
  'request_approval',
  // Desktop actuators: they act and return a status, they cannot read. They
  // are NOT floor-eligible -- at rank 505 they fail `isFloorEligible` -- but
  // they are correctly `inert` because they bring nothing in.
  'desktop_click',
  'desktop_type',
  'desktop_press_keys',
  'desktop_launch_app',
  'desktop_focus_window',
]);

/**
 * The classification. Note the polarity of the default: anything not declared
 * is `fetch`, the most conservative class. A newly registered tool is
 * therefore never floor-eligible and always forces the framed readers to
 * stay. Mis-declaring a new tool can cost tokens; it cannot open the
 * laundering door. `coverage.test.ts` still forces an explicit decision for
 * every builtin so the default is a safety net, not a way of avoiding review.
 */
export function outsideReach(tool: ToolDefinition): OutsideReach {
  if (SYNTHETIC_TOOLS.has(tool.name)) return 'inert';
  if (isUntrustedSourceTool(tool.name, tool.category)) return 'framed';
  if (NOT_REPLAY_DESPITE_APPEARANCES.has(tool.name)) return 'fetch';
  if (REPLAY_TOOLS.has(tool.name)) return 'replay';
  if (INERT_TOOLS.has(tool.name)) return 'inert';
  return 'fetch';
}

/**
 * True when the tool has an EXPLICIT entry in TOOL_ACTION_MAP.
 *
 * Deliberately `Object.hasOwn` and not the `if (TOOL_ACTION_MAP[name])` test
 * `getActionForTool` uses: that one is truthy for inherited keys, so a tool
 * called `constructor` would read as mapped. The divergence is on purpose -
 * do not "harmonise" this to match the other one.
 */
export function hasExplicitAction(tool: ToolDefinition): boolean {
  return Object.hasOwn(TOOL_ACTION_MAP, tool.name);
}

/**
 * Authority rank, with the one correction this filter needs.
 *
 * `getActionForTool` used to fall through to `read_data` (rank 100) for a
 * tool in neither action map, which scored an UNMAPPED SHELL as a level-1
 * read: both `manage_workflow` (category "automation") and `site_run_command`
 * (category "site-builder", a real `Bun.spawn(['sh','-c',cmd])`) were unmapped.
 * `builtin-tool-coverage.test.ts` existed to prevent exactly that and would
 * have caught it, but it walked BUILTIN_TOOLS and neither tool is in it.
 *
 * #503 closed both halves: all nine daemon-registered tools now carry
 * explicit entries, the coverage test derives its set from the real tool
 * factories rather than from BUILTIN_TOOLS, and the fallback itself fails
 * closed to `execute_command`.
 *
 * This function keeps rank Infinity for an unmapped tool regardless: never
 * floor-eligible, always an invariant trigger. The filter is built to be safe
 * in spite of the gap rather than to depend on it staying closed.
 */
export function authorityRank(tool: ToolDefinition): number {
  // Synthetic tools are rank 100 by fiat. They are not registry tools, so
  // they have no TOOL_ACTION_MAP entry and would otherwise take the
  // Infinity branch below and read as invariant TRIGGERS -- meaning the
  // escape hatch, present on every filtered turn by I4, would itself drag
  // the whole framed reader set back in and cancel the filter. They stay
  // out of the floor regardless, because `isFloorEligible` separately
  // demands an explicit action-map entry.
  if (SYNTHETIC_TOOLS.has(tool.name)) return severityRank('read_data');
  if (!hasExplicitAction(tool)) return Number.POSITIVE_INFINITY;
  return severityRank(getActionForTool(tool.name, tool.category));
}

/**
 * Rank of `read_data` (100): the ceiling for floor eligibility.
 *
 * An earlier version used `write_data` (302), which is Authority LEVEL 3 and
 * let `write_file` into the always-set: an unconstrained `path` resolved
 * against the default cwd with no traversal check, writing model-chosen
 * content, pinned into every turn including "set a goal to ship the release
 * this week". #483 requirement 4 asks that the always-set be the LOW
 * authority tools, and nothing about setting a goal needs an arbitrary file
 * write. The floor is for tools whose presence can never be the interesting
 * part of a turn.
 */
export const FLOOR_RANK_CEILING = severityRank('read_data');
/** Rank of `access_browser` (504). Retained for the invariant trigger test. */
export const PERCEPTION_RANK_CEILING = severityRank('access_browser');

/**
 * The always-offered set: low authority, explicitly gated, and incapable of
 * carrying outside text. #483 requirement 4 asks that the always-set be the
 * LOW-authority tools and that the privileged ones be what gets filtered;
 * this predicate is that requirement.
 */
export function isFloorEligible(tool: ToolDefinition): boolean {
  return outsideReach(tool) === 'inert'
    && hasExplicitAction(tool)
    && authorityRank(tool) <= FLOOR_RANK_CEILING;
}

/**
 * Framed tools whose point is to ACT, not to read. Never force-added by the
 * invariant repair, however their rank happens to fall.
 *
 * Rank alone was the first cut at "is this a reader", and it is wrong in one
 * direction: `browser_upload_file` maps to `write_data` (302), so it sits
 * BELOW the access_browser ceiling and a rank-only rule sweeps it into the
 * restored set. It sends a local file out. Auto-adding an exfiltration path
 * to every turn that happens to retain `run_command` is exactly the kind of
 * accidental capability grant this design is supposed to avoid, and it
 * contradicts the reason the 505/506 actors are excluded.
 *
 * Excluding a FRAMED tool from the union is always safe: it cannot create an
 * unframed route to outside content, which is the only thing I1 protects.
 * The tool stays selectable by the ordinary triggers, so a turn that really
 * needs to upload a file still gets it.
 */
const FRAMED_ACTORS: ReadonlySet<string> = new Set([
  // Sends a local file OUT. An exfiltration path, and one a rank test misses
  // entirely: it maps to write_data (302), so a `rank <= 504` rule sweeps it
  // into the restored set and auto-adds it to every turn that keeps the
  // shell.
  'browser_upload_file',
  // Replays a skill the person recorded earlier. Needs a pre-recorded skill
  // named in the owner's own catalogue, so it is not a reading route a model
  // substitutes toward.
  'run_skill',
  // Installs system-wide input hooks, and `start` always forces a
  // confirmation card. The worst possible thing to auto-add next to
  // `run_command` on a "run this script" turn.
  'record_skill',
]);

/**
 * A framed *reader*: the tools that give the model a wrapped, defanged,
 * taint-marking way to see something. These are what the invariant restores.
 *
 * Membership is "framed, minus a named list of actors". It is deliberately
 * NOT a rank test any more. Rank was wrong in both directions:
 *
 *   too permissive: `browser_upload_file` is 302 and got swept in.
 *   too strict:     `ui_act` is 505, but `get_value` is in its own
 *                   READ_ONLY_ACTIONS and its `authorityGate` returns null
 *                   for it -- 505 is the floor for the tool's WORST action,
 *                   not the rank of a read. `expand` and `scroll_into_view`
 *                   are likewise the only way to make collapsed or
 *                   off-surface content appear in the next `ui_snapshot`.
 *                   Excluding it left the desktop surface with framed eyes
 *                   and no framed hands: the model can see a collapsed
 *                   Details pane but not open it, and what it reaches for
 *                   instead is `capture_screen` / `desktop_screenshot`,
 *                   which are `fetch` and cannot be delimiter-framed. That
 *                   is the same substitution one surface sideways.
 *
 * `browser_evaluate` is included for the matching reason on the web surface:
 * it is framed and it is the only way to read state that `browser_snapshot`
 * cannot express (JS state, shadow DOM, a canvas-rendered table). It is
 * `execute_command`/506 -- exactly the same rank as `run_command` -- so
 * dropping it while keeping the shell is a rank TIE, not a step down, and
 * that is the substitution family this whole invariant exists to stop.
 */
export function isFramedPerception(tool: ToolDefinition): boolean {
  return outsideReach(tool) === 'framed' && !FRAMED_ACTORS.has(tool.name);
}

/**
 * Retaining any of these obliges the filter to retain every framed reader.
 *
 * Two clauses, and the second is not redundant:
 *   reach === 'fetch'   the laundering class proper (run_command, the
 *                       screenshots, delegation, list_directory, unmapped).
 *   rank > 504          everything above access_browser. Without this,
 *                       `S = FLOOR ∪ {desktop_click, desktop_type, ...}` with
 *                       no perception tool at all would be invariant-clean,
 *                       and that is the same substitution family one step
 *                       sideways (browser_click at 504 -> desktop_click at
 *                       505). It fails safe today only because `rawUiGate`
 *                       forces a review card on raw desktop mutations, which
 *                       is luck, not an invariant.
 */
export function isInvariantTrigger(tool: ToolDefinition): boolean {
  return outsideReach(tool) === 'fetch' || authorityRank(tool) > PERCEPTION_RANK_CEILING;
}
