import { afterAll, afterEach, beforeAll, beforeEach, expect, test } from "bun:test";
import { GlobalRegistrator } from "@happy-dom/global-registrator";
import type { Root } from "react-dom/client";
import { WorkflowCreationController, type CreationStorage } from "./controller";
import type { CompositionJob, CompositionRequest } from "./model";
import type { BriefShellPort, BriefRoute } from "../../contracts";
import type { WorkflowCreationBinding } from "./WorkflowCreationRoom";
let React:typeof import("react"),createRoot:typeof import("react-dom/client").createRoot,Room:typeof import("./WorkflowCreationRoom").WorkflowCreationRoom;
let root:Root,host:HTMLDivElement,binding:WorkflowCreationBinding,shell:BriefShellPort,requests:CompositionRequest[],routes:BriefRoute[];
const capabilities={contractVersion:1,capabilities:{workflowComposition:{supported:true,ready:true,enabled:true,state:"ready",reason:null}}};
const job=(r:CompositionRequest,patch:Partial<CompositionJob>={}):CompositionJob=>({jobId:"job-real",requestId:r.requestId,specification:{name:"New workflow",prompt:r.prompt},state:"queued",progress:{checkedCandidates:0},compositionId:null,workflow:null,blocker:null,createdAt:1,updatedAt:1,...patch});
beforeAll(async()=>{GlobalRegistrator.register();(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;React=await import("react");({createRoot}=await import("react-dom/client"));({WorkflowCreationRoom:Room}=await import("./WorkflowCreationRoom"));});
beforeEach(()=>{host=document.createElement("div");document.body.append(host);root=createRoot(host);requests=[];routes=[];let raw:string|null=null;const storage:CreationStorage={read:()=>raw,write:s=>{raw=s;}};
 binding={capabilities,controller:new WorkflowCreationController({submit:async r=>{requests.push(r);return job(r);},read:async()=>job(requests[0]!,{state:"draft_ready",workflow:{flowId:"generated-flow",versionId:"generated-version"}}),recover:async()=>null},storage,{source:"fixture",scopeId:"scope",requestId:()=>"request"}),recent:{source:"fixture",state:{status:"ready",data:[{flowId:"f",versionId:"v",runId:"r",name:"Failing workflow",status:"FAILED",result:"Mail sent!",at:1000,environment:"PRODUCTION"}]}}};
 shell={mode:"preview",route:{room:"workflows",selection:{}},sidebar:"expanded",chatOpen:false,theme:"light",setSidebar:()=>{},setChatOpen:()=>{},setTheme:()=>{},navigate:r=>routes.push(r)};
});
afterEach(async()=>{await React.act(async()=>root.unmount());binding.controller.dispose();host.remove();});afterAll(()=>GlobalRegistrator.unregister());
async function render(){await React.act(async()=>root.render(<div className="brief-root"><main className="brief-workspace-content"><Room shell={shell} binding={binding} reducedMotion/></main></div>));}
async function click(selector:string){await React.act(async()=>host.querySelector<HTMLButtonElement>(selector)!.click());}
test("suggestion only fills the shared composer and does not submit",async()=>{await render();await click('.brief-composer-suggestions button');expect(requests).toHaveLength(0);expect(host.querySelector<HTMLTextAreaElement>('textarea')?.value).toContain("After each meeting");expect(document.activeElement).toBe(host.querySelector('textarea'));});
test("burst sends once, then opens the returned flow AND version exactly once",async()=>{await render();await click('.brief-composer-suggestions button');await React.act(async()=>{const send=host.querySelector<HTMLButtonElement>('[aria-label="Send"]')!;for(let i=0;i<10;i++)send.click();});expect(requests).toHaveLength(1);await React.act(async()=>binding.controller.recover());expect(routes).toEqual([{room:"workflow-draft",selection:{flowId:"generated-flow",versionId:"generated-version"}}]);await render();expect(routes).toHaveLength(1);expect(host.querySelector<HTMLTextAreaElement>('textarea')?.value).toBe("");});
test("failed data can never show a success summary, and the whole row carries exact selection",async()=>{await render();expect(host.textContent).not.toContain("Mail sent!");expect(host.textContent).toContain("Run failed");await click('.brief-recent-row');expect(routes).toEqual([{room:"workflow",selection:{flowId:"f",versionId:"v",runId:"r"}}]);expect(binding.controller.getSnapshot().selectedRunId).toBe("r");expect(host.querySelector('.brief-recent-row')?.getAttribute('data-selected')).toBe("true");});
test("list return boundary does not clear prompt or selected row",async()=>{await render();await click('.brief-composer-suggestions button');await click('.brief-recent-row');await click('.brief-recent-workflows > .brief-button');expect(routes.at(-1)).toEqual({room:"all-workflows",selection:{}});await React.act(async()=>root.render(<div>Temporary other destination</div>));await render();expect(host.querySelector<HTMLTextAreaElement>('textarea')?.value).toContain("After each meeting");expect(host.querySelector('.brief-recent-row')?.getAttribute('data-selected')).toBe("true");});
test("disabled capability preserves the editable prompt but never submits",async()=>{binding.capabilities=null;await render();await React.act(async()=>binding.controller.setDraft("Keep me"));await click('[aria-label="Send"]');expect(requests).toHaveLength(0);expect(host.textContent).toContain("Workflow creation is unavailable");expect(host.querySelector<HTMLTextAreaElement>('textarea')?.value).toBe("Keep me");});
test("fixture data and controller never appear in live rooms",async()=>{shell.mode="live";await render();expect(host.querySelector('textarea')).toBeNull();expect(host.textContent).not.toContain("Failing workflow");});
test("failed receipts retain wording and render blockers as plain text",async()=>{binding.controller.port.submit=async r=>job(r,{state:"blocked",blocker:{code:"insufficient_information",message:"Choose destination",details:["<script>BAD</script>"]}});await render();await click('.brief-composer-suggestions button');await click('[aria-label="Send"]');expect(host.querySelector<HTMLTextAreaElement>('textarea')?.value).toContain("After each meeting");expect(host.textContent).toContain("Choose destination");expect(host.querySelector('script')).toBeNull();expect(routes).toHaveLength(0);});
test("loading, empty and unavailable recents remain distinct",async()=>{for(const status of ["loading","empty","unavailable"] as const){binding.recent={source:"fixture",state:status==="unavailable"?{status,reason:"offline"}:{status}};await render();expect(host.textContent).toContain(status==="loading"?"Loading recent runs":status==="empty"?"Your recent runs will appear":"Recent runs are unavailable");}});
test("no date, subtitle or global creation CTA returns",async()=>{await render();expect(host.querySelector('h1')?.textContent).toBe("Create your workflow");expect(host.textContent).not.toContain("Wednesday");expect(host.textContent).not.toContain("Turn a good conversation");expect(host.querySelectorAll('h1')).toHaveLength(1);});
test("loading history cannot erase a retained stream position before rows return",async()=>{
 const recent=binding.recent;binding.controller.savePosition(528,"r");binding.recent={source:"fixture",state:{status:"loading"}};await render();
 const scroll=host.querySelector<HTMLElement>('.brief-workspace-content')!;scroll.scrollTop=0;scroll.dispatchEvent(new Event('scroll'));expect(binding.controller.getSnapshot().scrollTop).toBe(528);
 binding.recent=recent;await render();await React.act(async()=>{await new Promise(r=>setTimeout(r,40));});expect(scroll.scrollTop).toBe(528);expect(binding.controller.getSnapshot().selectedRunId).toBe("r");
});

test("ingredient scope mismatch cannot expose another account's catalog",async()=>{
 binding.capabilities={...capabilities,capabilities:{...capabilities.capabilities,compositionIngredients:{supported:true,ready:true,enabled:true,state:"ready",reason:null}}};
 binding.ingredients={source:"fixture",scopeId:"foreign",state:"ready",choices:[{key:"private",displayName:"Other account private service",groupId:"private-service",group:"Private",tab:"connection",status:"missing-account"}]};
 await render();await click('[aria-label="Add connection or library node"]');expect(document.querySelector('[role="dialog"]')).toBeNull();expect(document.body.textContent).not.toContain('Other account private service');
});
test("selected ingredients without F08 cannot submit; explicit removal restores plain creation",async()=>{
 binding.controller.setIngredients([{displayName:"Gmail",selection:{kind:"connection",id:"gmail",pieceName:"gmail",pieceVersion:"1.0.0",required:true}}]);binding.controller.setDraft("Build");
 await render();await click('[aria-label="Send"]');expect(requests).toHaveLength(0);expect(host.textContent).toContain('Selected ingredients are unavailable');
 await click('[aria-label="Remove Gmail"]');await click('[aria-label="Send"]');expect(requests).toHaveLength(1);expect(requests[0]!.ingredients).toBeUndefined();
});
