#!/usr/bin/env bun
/**
 * Regenerate `src/authority/confusables-data.ts` from Unicode's UTS #39
 * `confusables.txt` (#794).
 *
 *   bun run scripts/gen-confusables.ts                 # fetch the pinned version
 *   bun run scripts/gen-confusables.ts ./confusables.txt   # or read a local copy
 *
 * The input is pinned by version and SHA-256, so a regeneration is either the
 * same bytes or a deliberate bump of both constants below.
 *
 * WHAT IS KEPT: all of it, every `MA` (mixed-script, any-case) mapping -- the
 * only table current releases carry -- as-is, with no iteration (the data is
 * already closed under mapping). The first cut kept only the mappings that
 * could reach an ASCII match and argued the rest could not change a result;
 * review found two ways they still could, through the fold the classifier
 * applies after the skeleton (a dropped mapping can turn a letter into edge
 * punctuation, or an unassigned-to-this-runtime character into a combining
 * mark the fold removes). The full table needs no such argument (#794 review).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const VERSION = '18.0.0';
const URL = `https://www.unicode.org/Public/${VERSION}/security/confusables.txt`;
const SHA256 = '6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92';
const OUT = join(import.meta.dir, '..', 'src', 'authority', 'confusables-data.ts');


/** A JS string literal of `s` using only printable ASCII: everything else as \u escapes. */
function asciiLiteral(s: string): string {
  let out = '';
  for (const unit of s.split('')) {
    const code = unit.charCodeAt(0);
    if (code >= 0x20 && code < 0x7f && unit !== "'" && unit !== '\\') out += unit;
    else out += `\\u${code.toString(16).padStart(4, '0')}`;
  }
  return `'${out}'`;
}

export function buildTable(text: string): Array<[string, string]> {
  const entries: Array<[string, string]> = [];
  for (const line of text.split('\n')) {
    const m = /^([0-9A-F]+) ;\t([0-9A-F ]+) ;\tMA\b/.exec(line);
    if (!m) continue;
    const source = String.fromCodePoint(parseInt(m[1]!, 16));
    const target = m[2]!.trim().split(' ').map((h) => String.fromCodePoint(parseInt(h, 16))).join('');
    entries.push([source, target]);
  }
  return entries.sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);
}

async function main(): Promise<void> {
  const local = process.argv[2];
  const bytes = local ? readFileSync(local) : Buffer.from(await (await fetch(URL)).arrayBuffer());
  const sha = createHash('sha256').update(bytes).digest('hex');
  if (sha !== SHA256) throw new Error(`confusables.txt ${VERSION}: expected sha256 ${SHA256}, got ${sha}`);
  const entries = buildTable(bytes.toString('utf8'));
  const body = entries.map(([s, t]) => `  [${asciiLiteral(s)}, ${asciiLiteral(t)}],`).join('\n');
  writeFileSync(OUT, `/**
 * GENERATED by scripts/gen-confusables.ts -- do not edit by hand.
 *
 * The UTS #39 confusable mappings (Unicode ${VERSION}, confusables.txt sha256
 * ${SHA256}): the whole MA table.
 * ${entries.length} entries. Unicode data, (c) Unicode, Inc., used under the Unicode
 * License v3 (https://www.unicode.org/license.txt).
 */
export const CONFUSABLES_VERSION = '${VERSION}';

export const CONFUSABLE_PROTOTYPES: ReadonlyArray<readonly [string, string]> = [
${body}
];
`);
  console.log(`wrote ${entries.length} entries to ${OUT}`);
}

if (import.meta.main) await main();
