#!/usr/bin/env bun
/**
 * Regenerate `src/authority/confusables-data.ts` from Unicode's UTS #39
 * `confusables.txt` (#794).
 *
 *   bun run scripts/gen-confusables.ts                 # fetch the pinned version
 *   bun run scripts/gen-confusables.ts ./confusables.txt   # or read a local copy
 *
 * The input is pinned by version and SHA-256, so a regeneration is either the
 * same bytes or a deliberate bump of both constants below.
 *
 * WHAT IS KEPT. `uiEffectHints` matches folded labels against ASCII patterns,
 * so the only mappings that can change a match are those whose prototype is
 * ASCII, plus every mapping FROM an ASCII character (`m` -> `rn`, `I` -> `l`,
 * `0` -> `O`, ...), which the skeleton applies to the patterns and the labels
 * alike. A mapping to a non-ASCII prototype leaves a non-ASCII character in the
 * skeleton either way, which no ASCII pattern can match, so dropping it changes
 * no result. Only the `MA` (mixed-script, any-case) table exists in current
 * releases; every entry is kept as-is, with no iteration (the data is already
 * closed under mapping).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const VERSION = '18.0.0';
const URL = `https://www.unicode.org/Public/${VERSION}/security/confusables.txt`;
const SHA256 = '6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92';
const OUT = join(import.meta.dir, '..', 'src', 'authority', 'confusables-data.ts');

const isAscii = (s: string) => [...s].every((ch) => ch.codePointAt(0)! < 0x80);

/** A JS string literal of `s` using only printable ASCII: everything else as \u escapes. */
function asciiLiteral(s: string): string {
  let out = '';
  for (const unit of s.split('')) {
    const code = unit.charCodeAt(0);
    if (code >= 0x20 && code < 0x7f && unit !== "'" && unit !== '\\') out += unit;
    else out += `\\u${code.toString(16).padStart(4, '0')}`;
  }
  return `'${out}'`;
}

export function buildTable(text: string): Array<[string, string]> {
  const entries: Array<[string, string]> = [];
  for (const line of text.split('\n')) {
    const m = /^([0-9A-F]+) ;\t([0-9A-F ]+) ;\tMA\b/.exec(line);
    if (!m) continue;
    const source = String.fromCodePoint(parseInt(m[1]!, 16));
    const target = m[2]!.trim().split(' ').map((h) => String.fromCodePoint(parseInt(h, 16))).join('');
    if (isAscii(source) || isAscii(target)) entries.push([source, target]);
  }
  return entries.sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);
}

async function main(): Promise<void> {
  const local = process.argv[2];
  const bytes = local ? readFileSync(local) : Buffer.from(await (await fetch(URL)).arrayBuffer());
  const sha = createHash('sha256').update(bytes).digest('hex');
  if (sha !== SHA256) throw new Error(`confusables.txt ${VERSION}: expected sha256 ${SHA256}, got ${sha}`);
  const entries = buildTable(bytes.toString('utf8'));
  const body = entries.map(([s, t]) => `  [${asciiLiteral(s)}, ${asciiLiteral(t)}],`).join('\n');
  writeFileSync(OUT, `/**
 * GENERATED by scripts/gen-confusables.ts -- do not edit by hand.
 *
 * The UTS #39 confusable mappings (Unicode ${VERSION}, confusables.txt sha256
 * ${SHA256}) that can affect an ASCII match: every mapping
 * from an ASCII character, and every mapping to an all-ASCII prototype.
 * ${entries.length} entries. Unicode data, (c) Unicode, Inc., used under the Unicode
 * License v3 (https://www.unicode.org/license.txt).
 */
export const CONFUSABLES_VERSION = '${VERSION}';

export const CONFUSABLE_PROTOTYPES: ReadonlyArray<readonly [string, string]> = [
${body}
];
`);
  console.log(`wrote ${entries.length} entries to ${OUT}`);
}

if (import.meta.main) await main();
